### ISSUE TITLE
Add readme file with installation steps.

### ISSUE THREAD

**Issue by Shadyelgewily** [markkvdb/ghoR#1]
I could not install the package because I did not have Devtools installed, did not have the latest version of roxygen2 package and because the folder "inst/" was not created on my computer locally.

**Comment by markkvdb** [comment]
Devtools, usethis roxygen2 and testthat are essential for developing packages. So I suggest to download these. Note that this is not important for the end user since they do not need these tools to uses the final package.

**Comment by markkvdb** [comment]
The readme should not be written directly but with a `Rmd` file instead. When we build the package this will result in building this Rmarkdown file which will create the md file for us. I cannot find the resource online to do this right now but I saw it was possible.

**Comment by markkvdb** [comment]
Made a start with the documentation in f5c3c47. You can simply edit the `README.Rmd` file to update the README
