### ISSUE TITLE
Expose necessary functions

### ISSUE THREAD

**Issue by markkvdb** [markkvdb/ghoR#5]
At the moment, all functions will be exported with the function. This is not necessary since all functions in the utils.R file are only for internal use for the package. Users should only be exposed to the functions defined in `load_indicator.R` (for now). 

We have to figure out how to fix this.

**Comment by Shadyelgewily** [comment]
https://r.789695.n4.nabble.com/Proper-way-to-implement-package-internal-functions-td4669360.html

This topic provides some information on how to do this.

**Comment by Shadyelgewily** [comment]
See topic "Keyword internal" in the section Roxygen comments on the link http://r-pkgs.had.co.nz/man.html. Perhaps we can achieve what you want with these settings.
