### ISSUE TITLE
Improve caching

### ISSUE THREAD

**Issue by markkvdb** [markkvdb/ghoR#6]
Datasets are now saved as JSON files in the `inst` folder but I do not know if this is best practice. Furthermore, we only import the json files once and do not check if there is a new version available for download. Another strategy would be to remove the file on the user's computer after some time period (say a week).

**Comment by Shadyelgewily** [comment]
I would suggest for now to have a settings file, where the user can specify the number of days the data file is stored on the computer. When the data is removed, the next time the user uses the package, the file is downloaded and stored again.

**Comment by markkvdb** [comment]
This problem has been solved. The only issue remaining is to update the file if the update date of the local dataset is before the last update of WHO.
